[build]
  publish = "client/"

[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/pages/404.html"
  status = 404
  force = false